### ISSUE TITLE
Cert directory not created on master

### ISSUE THREAD

**Issue by seidler2547** [fraenki/puppet-acme#10]
I am getting this error on the first issue of a certificate:
`Notice: /Stage[main]/Acme::Request::Handler/Acme::Request[www.example.com]/Exec[issue-certificate-www.example.com]/returns: /opt/acme.sh/acme.sh: 4678: /opt/acme.sh/acme.sh: cannot create /etc/acme.sh/certs/www.example.com/cert.pem: Directory nonexistent`
I need to manually create the directory `/etc/acme.sh/certs/www.example.com` to make it work.

**Comment by fraenki** [comment]
This was fixed in https://github.com/fraenki/puppet-acme/commit/a8b081bf002942837af044a479fdc7c0eeaa2d36.
