### ISSUE TITLE
Certificates on the master node error out due to duplicate resources

### ISSUE THREAD

**Issue by oxc** [fraenki/puppet-acme#20]
The commit a8b081b from #11 breaks certificate generation on the master node due to duplicate resource generation.
The certs dir is defined both in csr.pp and request.pp

**Comment by fraenki** [comment]
@oxc Does https://github.com/fraenki/puppet-acme/commit/f164cd1f23a3b6791bc55f39065fffd71fe220f4 fix the issue for you?

**Comment by fraenki** [comment]
Should be fixed in version 1.0.4.
