### ISSUE TITLE
NSUPDATE_SERVER - Resource type not found

### ISSUE THREAD

**Issue by advorkin** [fraenki/puppet-acme#23]
Hello,

I'm getting the following error message with below code and would appreciate your assistance.  

Thank you.

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Resource type not found: NSUPDATE_SERVER (file: /etc/puppetlabs/code/environments/puppet/site-modules/profiles/manifests/puppetboard.pp, line: 31, column: 13) on node puppet

```
    class { 'acme':
      accounts => ['myemail@email.com'],
      profiles => {
        nsupdate_example => {
          challengetype => 'dns-01',
          hook          => 'nsupdate',
          env           => {
            NSUPDATE_SERVER => 'dns.example.com'
          },
          options       => {
            dnssleep      => 5,
            nsupdate_id   => 'acme-update',
            nsupdate_type => 'hmac-sha512',
            nsupdate_key  => '`123456',
          }
        }
      }
    }
```

**Comment by fraenki** [comment]
Thanks for bringing this to my attention. I've configured everything in Hiera, so I haven't noticed the broken example in the README. It should work if you modify it like this:

```
          env           => {
            'NSUPDATE_SERVER' => 'dns.example.com'
          },
```

I couldn't find an explanation for this behaviour.

Can you confirm that it's working now?

**Comment by advorkin** [comment]
Thank you, that works!  I have another question and will submit a different bug report.  I appreciate your help.

**Comment by advorkin** [comment]
Problem solved.  Thank you!
