### ISSUE TITLE
Configurable exec timeout and dnssleep

### ISSUE THREAD

**Issue by qroac** [fraenki/puppet-acme#28]
First of all, thank you for this opportunity for central certificate management with puppet.

I use this module with ISPConfig dns plugin.  
For issuing certificates, I noticed two problems with puppet-acme:

**Configurable timeout for EXEC "issue-certificate-${domain}"**  
Publishing the dns record via ISPConfig and from there to an external slave DNS provider takes time.
The default timeout of 300 is not always enough.

**Param dnssleep should be optional**  
If not provided or set to e.g false/-1, do not prepend --dnssleep to the command. This way acme.sh can recheck the dns entry periodically and finish after success or will be terminated when EXEC timeout is exceeded.

At the moment I run the issuing command by hand on the puppet master. The last certificate took about 7 minutes to be issued. Too much for default exec runtime.

**Comment by fraenki** [comment]
Your timing is great, I'm currently preparing a new major release so there was still time to implement your suggestions.

> Configurable timeout for EXEC "issue-certificate-${domain}"

Implemented in https://github.com/fraenki/puppet-acme/commit/cec79d09640d85d8669805704a266fd6ed969930. The new parameter `$exec_timeout` can be used to change this setting. The default timeout was increased to 3600 seconds.

> Param dnssleep should be optional

Implemented in https://github.com/fraenki/puppet-acme/commit/41dfe4505c05a8f45c27439ecb39e26706e0abb4. Now setting `$dnssleep` to `0` effectively disables the sleep mechanism and lets acme.sh poll DNS status automatically.

Please let me know if it doesn't work as expected.

**Comment by qroac** [comment]
Wow. That is a blazing fast reaction ;)

Thank you for implementing this. Looking forward to your next release :)
