### ISSUE TITLE
deprecated option for acme.sh

### ISSUE THREAD

**Issue by ashish1099** [fraenki/puppet-acme#32]
Currently module has these options `--fullchainpath` but master acme.sh has `--fullchain-file`.

so is it on purpose that we it depends on older version of acme.sh ?

https://github.com/acmesh-official/acme.sh/commit/5c539af7d7645723b928389bc93da526f0dcfa60

**Comment by fraenki** [comment]
> so is it on purpose that we it depends on older version of acme.sh ?

The module does not depend on an old version. These deprecated options work perfectly fine even with the current devel version of acme.sh.

However, thanks for bringing this to my attention, I will replace the deprecated options in the next release.
