### ISSUE TITLE
Dns-01 issues 

### ISSUE THREAD

**Issue by tenajsystems** [fraenki/puppet-acme#5]
Getting issues when i run puppet to get letsencrypt ssl cert. Below are the errors. How do I fix this issue?

[Mon Sep 18 15:59:29 EDT 2017] you must specify a path to the nsupdate key file
[Mon Sep 18 15:59:29 EDT 2017] Error add txt for domain:_acme-challenge.[domain_Name]

**Comment by tenajsystems** [comment]
How do I work around updating DNS when I don't have control over DNS?

**Comment by fraenki** [comment]
> How do I work around updating DNS when I don't have control to DNS?

This module is currently limited to the DNS-01 challenge type. Other challenge types are not supported.
